import type { Metadata } from "next";
import { Nunito, Libre_Baskerville } from "next/font/google";
import "./globals.css";

const main_font = Nunito({ subsets: ["latin"], variable: "--main-font" });
const secondary_font = Libre_Baskerville({
  subsets: ["latin"],
  variable: "--secondary-font",
  weight: "400",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${main_font.variable} ${secondary_font.variable}`}>
        {children}
      </body>
    </html>
  );
}
